package com.future.getd.net.model;


/**
 * A completion generated by OpenAI
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
public class CompletionChoice {
    ////    "choices": [
    ////        {
    ////            "index": 0,
    ////            "message": {
    ////                "role": "assistant",
    ////                "content": "你好！安卓（Android）是一款由谷歌开发的基于Linux内核的开源操作系统，主要用于智能手机和平板电脑。以下是一些关键点：\n\n1. **开放源代码**：安卓是开源的，其源代码在GitHub的Android Open Source Project (AOSP)上公开。这意味着开发者可以自由地修改和分发安卓系统。\n\n2. **应用生态系统**：安卓拥有丰富的应用生态系统，用户可以通过Google Play商店或者其他第三方应用商店下载和安装各种应用程序。\n\n3. **自定义功能**：安卓系统允许用户和制造商进行高度自定义，用户可以更改系统的主题、图标和设置。\n\n4. **多种设备支持**：除了智能手机和平板电脑，安卓还广泛应用于智能手表（通过Wear OS）、电视（通过Android TV）、汽车（通过Android Auto）等设备。\n\n5. **更新和安全性**：谷歌定期发布安卓系统更新，包括重大系统升级和安全补丁。\n\n如果你有任何关于安卓系统的具体问题或需要帮助的地方，请告诉我！",
    ////                "refusal": null
    ////            },
    ////            "logprobs": null,
    ////            "finish_reason": "stop"
    ////        }
    ////    ],
    /**
     * The generated text. Will include the prompt if {@link CompletionRequest#echo } is true
     */
//    String text;

    /**
     * This index of this completion in the returned list.
     */
    Integer index;

    Message message;

    /**
     * The log probabilities of the chosen tokens and the top {@link CompletionRequest#logprobs} tokens
     */
//    LogProbResult logprobs;

    /**
     * The reason why GPT stopped generating, for example "length".
     */
    String finish_reason;

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getFinish_reason() {
        return finish_reason;
    }

    public void setFinish_reason(String finish_reason) {
        this.finish_reason = finish_reason;
    }

    public Message getMessage() {
        return message;
    }

    public void setMessage(Message message) {
        this.message = message;
    }

    @Override
    public String toString() {
        return "CompletionChoice{" +
                "index=" + index +
                ", message=" + message +
                ", finish_reason='" + finish_reason + '\'' +
                '}';
    }
}
